### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by ADsuper** [leonHua/LGank#2]
福利页面 三个布局方式切换，最后一个切换到第一个的时候会崩溃，环境：荣耀V8，API 25

**Comment by leonHua** [comment]
@ADsuper 已经修复，代码已经更新，APK下载文件需要签名文件，明天会更新，欢迎继续使用。如能继续反馈，将不胜感激，谢谢

**Comment by ADsuper** [comment]
客气客气，我忘记在哪看到你发的 github 链接了，就拿来学习学习！

**Comment by ADsuper** [comment]
另外还有一个下拉加载更多的时候，加载更多的 ui 会覆盖掉页面显示的最后一个 item
