### ISSUE TITLE
优化

### ISSUE THREAD

**Issue by ADsuper** [leonHua/LGank#3]
大神，下拉加载更多的时候，加载更多的 ui 会覆盖掉页面显示的最后一个 item

**Comment by leonHua** [comment]
@ADsuper 看到啦，最近时间紧，抽空会把这个解决掉哒，感谢支持，继续关注哦

**Comment by ADsuper** [comment]
木事，我会给你一直找 bug 的

**Comment by leonHua** [comment]
已修复
