### ISSUE TITLE
优化2

### ISSUE THREAD

**Issue by ADsuper** [leonHua/LGank#4]
福利页面，下拉加载图片的时候，瀑布流效果中，会出现已经加载出来的图片和占位图混乱现象，就是：图片已经加载出来了，但是还会闪一下占位图，而其他的两种布局效果没出现这种情况，我想应该是你设置瀑布流效果的时候出现的问题

**Comment by leonHua** [comment]
瀑布流高度是随机算的，这种情况会在瀑布流最后一个没占满的情况，都是随机的高度可能导致会重新加载。可以使用图片的高度，但是gank的图片好像高度都差不多，这样瀑布流的效果看不出来，所以就先这样吧~~~
