### ISSUE TITLE
崩溃2

### ISSUE THREAD

**Issue by ADsuper** [leonHua/LGank#5]
福利页面，点击 FloatingActionButton 的时候，如果目前就是 线性布局 ，再次点击线性布局按钮，会崩溃，没有抓 log ，自己试试哈  0.0

**Comment by leonHua** [comment]
就服你。。。
这个增加了判断，如果是当前的模式就不在重复加载了，目前我这没问题，你看下还会出问题不，Thanks

**Comment by ADsuper** [comment]
这个没啥问题了
