### ISSUE TITLE
优化加载更多

### ISSUE THREAD

**Issue by ADsuper** [leonHua/LGank#6]
目前的加载更多布局不稳定，有时候会正常显示在 recyclerView 下方，有时候仍然会覆盖掉 RecyclerView 条目

**Comment by ADsuper** [comment]
比如说，慢慢拉到最后一个条目的时候，就会出现覆盖情况

**Comment by leonHua** [comment]
这个目前是通过布局方式实现上拉加载，判断列表到最后一个条目的时候显示加载更多，慢慢拉会出现这个问题，我让它自动滚动上去了。更好的方式是给列表添加footer，整体算到recyclerview里，但是改动会比较大，可以考虑使用第三方库，目前先这样把。
