### ISSUE TITLE
搜索页面

### ISSUE THREAD

**Issue by ADsuper** [leonHua/LGank#7]
1. 搜索结果完成之后，下拉至最后一个条目，加载更多没有更多数据时，仍然出现加载更多的动画和 ui ；

2.当出现第一种情况时，再次使用搜索功能时，无法搜到任何东西，显示白板页面；

3.当搜索结果的条目未撑满整个屏幕时，上拉和下拉时，界面会出现闪跳现象。例如搜索 “1112”，只有一个条目，

目前就发现了这三个  0.0

**Comment by leonHua** [comment]
恩，这个我之前没测到，已经修复，你在试试，thanks
