### ISSUE TITLE
你好，项目运行不了~

### ISSUE THREAD

**Issue by qzqs** [leonHua/LGank#9]
下载下来运行代码，Skin的几个包都提示找不到，不知道怎么去解决。
Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:compileDebugSources, :app:compileDebugAndroidTestSources, :app:compileDebugUnitTestSources, :skinblue:generateDebugSources, :skinblue:generateDebugAndroidTestSources, :skinblue:mockableAndroidJar, :skinblue:prepareDebugUnitTestDependencies, :skinblue:compileDebugSources, :skinblue:compileDebugAndroidTestSources, :skinblue:compileDebugUnitTestSources, :skinpick:generateDebugSources, :skinpick:mockableAndroidJar, :skinpick:prepareDebugUnitTestDependencies, :skinpick:generateDebugAndroidTestSources, :skinpick:compileDebugSources, :skinpick:compileDebugUnitTestSources, :skinpick:compileDebugAndroidTestSources, :skinpurple:generateDebugSources, :skinpurple:generateDebugAndroidTestSources, :skinpurple:mockableAndroidJar, :skinpurple:prepareDebugUnitTestDependencies, :skinpurple:compileDebugSources, :skinpurple:compileDebugAndroidTestSources, :skinpurple:compileDebugUnitTestSources, :skinred:generateDebugSources, :skinred:mockableAndroidJar, :skinred:prepareDebugUnitTestDependencies, :skinred:generateDebugAndroidTestSources, :skinred:compileDebugSources, :skinred:compileDebugUnitTestSources, :skinred:compileDebugAndroidTestSources, :skinyellow:generateDebugSources, :skinyellow:generateDebugAndroidTestSources, :skinyellow:mockableAndroidJar, :skinyellow:prepareDebugUnitTestDependencies, :skinyellow:compileDebugSources, :skinyellow:compileDebugAndroidTestSources, :skinyellow:compileDebugUnitTestSources]

**Comment by leonHua** [comment]
skin主题皮肤工程都和APP在同一个目录下，你看看是不是没有导入

**Comment by qzqs** [comment]
已经解决，感谢
